name: Enerflux Data Machine (daily test)

on:
  workflow_dispatch:  # bouton "Run workflow" manuel
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC (optional)

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure we get all history/branches

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Cache pip for faster installs

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found, installing basic packages"
            pip install pandas requests
          fi

      - name: Prepare output dir
        run: mkdir -p pipeline/outputs

      - name: Debug tree
        run: |
          echo "Current directory:"
          pwd
          echo "Contents:"
          ls -la
          echo "----- pipeline directory -----"
          ls -la pipeline/ || true
          echo "----- pipeline/outputs -----"
          ls -la pipeline/outputs/ || true
          echo "----- fred_wti.py check -----"
          if [ -f "pipeline/collectors/fred_wti.py" ]; then
            echo "fred_wti.py exists, showing relevant lines:"
            grep -n "to_csv\|mkdir\|out" pipeline/collectors/fred_wti.py || true
          else
            echo "fred_wti.py not found!"
            find . -name "*.py" | head -10
          fi

      - name: Run daily job (WTI only for test)
        run: |
          # First test if the file exists and can run
          if [ -f "ci_run.py" ]; then
            python ci_run.py daily
          else
            echo "ci_run.py not found, running fred_wti.py directly"
            python pipeline/collectors/fred_wti.py
          fi
