name: Enerflux Data Machine (daily test)

on:
  workflow_dispatch:  # bouton "Run workflow" manuel

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily job (WTI only for test)
        run: |
          python ci_run.py daily
