name: Enerflux Data Machine

on:
  workflow_dispatch:
    inputs:
      job:
        description: "Job to run"
        type: choice
        required: true
        default: daily
        options:
          - daily
          - weekly
  schedule:
    - cron: '0 0 * * *'      # Daily à 00:00 UTC (01:00 à Tunis)
    - cron: '30 5 * * MON'   # Weekly le lundi 05:30 UTC

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas requests boto3 botocore matplotlib

      - name: Prepare output dir
        run: mkdir -p pipeline/outputs

      - name: Debug tree (first runs only - optional)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          pwd
          ls -la
          echo "----- pipeline -----"; ls -la pipeline || true
          echo "----- outputs  -----"; ls -la pipeline/outputs || true

      - name: Run pipeline (daily/weekly)
        env:
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: |
          job="${{ inputs.job }}"
          if [ -z "$job" ]; then
            # si CRON: weekly le lundi 05h30 UTC, sinon daily
            day=$(date -u +%u); hour=$(date -u +%H%M)
            if [ "$day" = "1" ] && [ "$hour" = "0530" ]; then
              job="weekly"
            else
              job="daily"
            fi
          fi
          echo "Running job=$job"
          python ci_run.py "$job"
